config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
   root "items#index"
   get "items/filter", to: 'items#filter'
   resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
	  scope :by_category, ->(cat) { where(category: cat) if cat.present? }
	  paginates_per 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
      @items = Item.page(params[:page]).per(10).order(created_at: :desc)
  end

  def filter
    @items = Item.by_category(params[:category]).page(params[:page]).per(10)
    respond_to do |format|
      format.js
      format.html { render partial: "items", locals: { items: @items } }
    end
  end

  def show
    @item = Item.find(params[:id])
     respond_to do |format|
      format.js
    end
end

def edit
  @item = Item.find(params[:id])
  respond_to do |format|
    format.js
  end

end

def update
  @item = Item.update(items_params)
  if @item.update
    respond_to do |format|
    format.js
    end
end
end

def new
  @item = Item.new
    respond_to do |format|
    format.js
  end
end

def create
  @item = Item.create(items_params)
  if @item.save
    respond_to do |format|
      format.turbo_stream
    end
  end
end

def edit
  @item = Item.find(params[:id])
end

def update
  @item = Item.find(params[:id])
  if @item.update(items_params)
    respond_to do |format|
      format.js
      end
  end
end

def destroy
  @item = Item.find(params[:id])
  @item.destroy
      respond_to do |format|
      format.js 
    end
end
private 
def items_params
    params.require(:item).permit(:name, :category)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_create.html.erb
<div>  <%= link_to item.name, "javascript:void(0);", class: 'show-link', data: { id: item.id }%>- <%= item.category %></div>

app/views/items/_filter.html.erb
<%= render partial: "items", locals: { items: @items } %>

app/views/items/_form.html.erb
  <%= form_with model: item, remote: true do |form| %>
<div>
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>

<div>
  <%= form.label :category %>
  <%= form.text_field :category %>
</div>
  <%= form.submit "submit" %>
<% end %>

app/views/items/_items.html.erb
<% if items.any? %>
  <% items.each do |item| %>
  <div>  <%= link_to item.name, "javascript:void(0);", class: 'show-link', data: { id: item.id }%>- <%= item.category %></div>
  <% end %>
<% else %>
  <p>No items found.</p>
<% end %>
<div class="pagination">
  <%= paginate @items %>
</div>

app/views/items/_show.html.erb
<%= item.id %>

<%= link_to "back", "javascript:void(0);", class: 'back-link'%>
<%= button_to "delete", item_path(item.id), method: :delete, class: 'delete-btn', remote: true %>
<%= link_to "edit", "javascript:void(0);", class: 'edit-link', data:{id: item.id} %>

<script>
  $('.edit-link').on('click',function () {
    var id = $(this).data('id');
    $.ajax({
      url: '/items/' + id+'/edit',
      method: 'GET',
      dataType: 'script'
    });
  });
</script>

app/views/items/create.js.erb
$('#new-item-data').append('<%= j render partial: "items", locals: {item: @item}%>');

app/views/items/create.turbo_stream.erb
<%= turbo_stream.append 'items-container', partial: 'create', locals: { item: @item } %>

app/views/items/edit.js.erb
$('#edit-form').html('<%= j render partial: "form", locals: { item: @item } %>');

app/views/items/filter.js.erb
$('#items-container').html('<%= j render partial: "items", locals: { items: @items } %>');

  $('.show-link').on('click',function (e) {
  	e.preventDefault();

    var id = $(this).data('id');
    $.ajax({
      url: '/items/' + id,
      method: 'GET',
      dataType: 'script'
    });
  });

app/views/items/index.html.erb
<h1>Items</h1>

<h3><%= link_to "new item", "javascript:void();", class: 'new-item-link' %></h3>

<!-- Button to trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newItemModal">
  Launch Modal
</button>

<!-- Modal HTML -->
<div class="modal fade" id="newItemModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <!-- Modal Header -->
      <div class="modal-header">
        <h5 class="modal-title" id="newItemModalLabel">NEW ITEM</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      
      <!-- Modal Body -->
      <div class="modal-body">
           <%= form_with(model: Item.new, url: items_path, method: :post, remote: true) do |f| %>
          <div class="mb-3">
            <%= f.label :Name %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= f.label :Category %>
            <%= f.text_area :category, class: "form-control" %>
          </div>
          <%= f.submit "Create", class: "btn btn-primary" %>
        <% end %>
      </div>
      
      <!-- Modal Footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>

    </div>
  </div>
</div>



<div id="new-form"></div>
<div id="edit-form"></div>
<div>
  <button data-category="Electronics" class="filter-btn">Electronics</button>
  <button data-category="Furniture" class="filter-btn">Furniture</button>
  <button data-category="Education" class="filter-btn">Education</button>
  <button data-category="" class="filter-btn">All</button>
</div>


<div id="items-container">
  <%= render partial: 'items', locals: { items: @items } %>
</div>

<div id="new-item-data"></div>

<div id="items-container">
    

</div>

app/views/items/new.js.erb
$('#new-form').html('<%= j render partial: "form", locals: { item: @item } %>');

app/views/items/show.html.erb
Name<%= item.name %>

app/views/items/show.js.erb
$('#items-container').html('<%= j render partial: "show", locals: { item: @item } %>');

  $('.back-link').on('click', function () {
    $.ajax({
      url: '/items/filter',
      method: 'GET',
      dataType: 'script',
    });
  });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ajax Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">


  </head>

  <body>
    <%= yield %>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

  </body>
</html>